Update 1-install_load_balancer

diff --git a/load_balancer/1-install_load_balancer b/load_balancer/1-install_load_balancer
--- a/load_balancer/1-install_load_balancer
+++ b/load_balancer/1-install_load_balancer
@@ -1,28 +1,29 @@
 #!/usr/bin/env bash
-# Create a script to install and configure HAProxy on lb-01 server
-# Configure HAProxy to send traffic to web-01 and web-02 servers
-# Distribute requests using a roundrobin algorithm
-# Make sure that HAProxy can be managed via an init script
-# Install and configure HAproxy on my lb-01 server.
-sudo apt-get -y update
-apt-get -y install haproxy
+# This script configures Nginx to add a custom HTTP header with the server's hostname
 
-# edit config file
-server_config=\
-"
-frontend supserrr-frontend
-        bind *:80
-        mode http
-        default_backend oreste-backend
-backend supserrr-backend
-        balance roundrobin
-        server 6485-web-01 3.86.231.113:80 check
-        server 6485-web-02 3.83.164.61:80 check
-"
-echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
+# Update package list and install Nginx
+echo "Updating package list and installing Nginx..."
+sudo apt update -y
+sudo apt install nginx -y
 
-# enable haproxy to be started by init script
+# Get the hostname of the server
+HOSTNAME=$(hostname)
+echo "Host name is: $HOSTNAME"
 
-echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
+# Modify Nginx configuration to add the custom header
+echo "Modifying Nginx configuration..."
+sudo sed -i "/server_name _;/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
 
-sudo service haproxy restart
+# Test the Nginx configuration to ensure it's valid
+echo "Testing Nginx configuration..."
+sudo nginx -t
+
+# If the configuration test is successful, restart Nginx to apply changes
+if [ $? -eq 0 ]; then
+    echo "Nginx configuration is valid. Restarting Nginx..."
+    sudo systemctl restart nginx
+    echo "Nginx restarted successfully."
+else
+    echo "Nginx configuration test failed. Please check the configuration."
+    exit 1
+fi
